apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: profile-stats-secrets
  namespace: profile-stats
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: profile-stats-secrets
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_PAT
      remoteRef:
        key: profile-stats
        property: GITHUB_PAT
    - secretKey: UPTIME_KUMA_API_KEY
      remoteRef:
        key: profile-stats
        property: UPTIME_KUMA_API_KEY
